version: "3.3"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: dianjianbiao_backend
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: dianjianbiao_frontend
    ports:
      - "3000:3000"
    restart: always